/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private String s;

    public final String getGreeting() {
        return "Hello world.";
    }

    public static String shout(final String str) {
        return str + "_shout";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
